-- Environment variables.
--
-- Sourced from hyprland.lua before any other config, so use this for
-- variables the rest of the config reads. Only read if the file exists.
--
-- This copy in the repo is an EMPTY TEMPLATE. The installer copies it only
-- when ~/.config/hypr/custom/ does not already exist (mode: skip-if-exists),
-- so your own values are never overwritten by a re-run.
--
-- Uncomment and edit as needed:

-- hl.variable("MYAPP_CONFIG", "/path/to/config")
