-- Exec-once commands and startup entries.
--
-- Sourced from hyprland.lua after hyprland/execs.lua, so these run in
-- addition to the defaults. Only read if the file exists.
--
-- This copy in the repo is an EMPTY TEMPLATE. The installer copies it only
-- when ~/.config/hypr/custom/ does not already exist (mode: skip-if-exists),
-- so your own entries are never overwritten by a re-run.
--
-- Uncomment and edit as needed:

-- hl.exec_cmd("notify-send 'Hello' 'world' -a 'Custom'")
